### ISSUE TITLE
`Crash 1.19.4` Game crashes during world loading, is related to the config screen

### ISSUE THREAD

**Issue by zndrmn** [FamroFexl/ForceCrawl#2]
Minecraft 1.19.4
ForceCrawl 1.0.2
oωo-lib 0.10.3
Fabric 0.14.19
Fabric API 0.78.0

[latest.log](https://gist.github.com/zndrmn/3b954265b56f1e35ea873a197adbf8b9#file-gistfile1-txt-L2125)
[crash-2023-04-17_17.31.26-client.txt](https://gist.github.com/zndrmn/1ed96afc14d7ef1c3c2e003ca9fdd598)

**Comment by FamroFexl** [comment]
1.19.4+ isn't currently supported and won't be until 1.20 officially releases. Unless you require multiplayer functionality, 1.0.1/1.0.0 should work as a temporary solution
