### ISSUE TITLE
Misplaced configuration file on non-Windows systems

### ISSUE THREAD

**Issue by ghost** [FamroFexl/ForceCrawl#4]
The configuration file gets saved as a file named `config\forcecrawl.cfg` on non-Windows systems. This is caused by [this line](https://github.com/FamroFexl/ForceCrawl/blob/1.20-fabric/src/main/java/com/fexl/forcecrawl/config/ConfigOptions.java#L16) which assumes the file separator is a backslash, which (to my knowledge) is a Windows only thing.
This can be fixed by replacing the line with either of these:
```java
// This should still work on Windows systems, but might not on some other systems
public static File configFile = new File(FabricLoader.getInstance().getConfigDir() + "/forcecrawl.cfg");
```
```java
// This ensures using the correct separator on every system
public static File configFile = new File(FabricLoader.getInstance().getConfigDir() + File.separator + "forcecrawl.cfg");
```
```java
// This uses the fact FabricLoader#getConfigDir() returns a Path object
public static File configFile = FabricLoader.getInstance().getConfigDir().resolve("forcecrawl.cfg").toFile();
```
<details><summary>Attached is a screenshot of my .minecraft folder</summary>

![image](https://github.com/FamroFexl/ForceCrawl/assets/25990664/5a805658-fd36-4eee-9d49-8647617b4efe)
</details>

As this does not break the loading/saving of the config, I would understand if it were a low priority issue.

**Comment by FamroFexl** [comment]
This will be fixed in the next release.
