### ISSUE TITLE
Not a bug, but a design suggestion!

### ISSUE THREAD

**Issue by yermachello** [FamroFexl/ForceCrawl#5]
I wanna contribute to the mod and encourage it's support, for me and my friends this mod is essential. Contact me on discord, I'd be glad to make some adjustments: yermak

![Artboard 3](https://github.com/FamroFexl/ForceCrawl/assets/7390018/078f195f-2a5e-418f-8c18-431e31527d2a)
![Artboard 3_1](https://github.com/FamroFexl/ForceCrawl/assets/7390018/914dec4d-e4ff-40ad-9a15-ef8a0adeed24)

**Comment by FamroFexl** [comment]
My Discord: famrofexl

I would appreciate your contributions and thoughts!
