### ISSUE TITLE
[Bug]: Server Crashes

### ISSUE THREAD

**Issue by TheRubyGames** [FamroFexl/ForceCrawl#8]
### Describe the Bug

Installed mod on the client, worked perfect however the hitbox didn't work as intended so I installed it on the server and as soon as I log on, and attempt to move, the server crashes.

### Mod version(s) affected

1.0.4

### Mod loader(s) used

Fabric

### Minecraft version(s) used

1.21

### Other mods used

<li>Entity Model Features [2.1]</li> 	<li>Amplified Nether [1.2.5]</li> 	<li>Sodium Extra [0.5.7+mc1.21]</li> 	<li>Lithium [0.12.5]</li> 	<li>EntityCulling [1.6.6]</li> 	<li>essential-container [1.0.0]</li> 	<li>Mod Menu [11.0.0-beta.2]</li> 	<li>Nullscape [1.2.6]</li> 	<li>Chat Heads [0.12.3]</li> 	<li>Mouse Tweaks [2.26]</li> 	<li>Sodium [0.5.9+mc1.21]</li> 	<li>Yet Another Minecraft BINGO [1.5.0+mc1.21.0]</li> 	<li>Fabric API [0.100.1+1.21]</li> 	<li>Architectury [13.0.1]</li> 	<li>YetAnotherConfigLib [3.5.0+1.21-fabric]</li> 	<li>Visuality [0.7.4+1.21]</li> 	<li>Terralith [2.5.3]</li> 	<li>Sound Physics Remastered [1.21-1.4.3]</li> 	<li>Xaero's Minimap [24.2.1]</li> 	<li>Jade [15.0.4+fabric]</li> 	<li>Freecam [1.3.0-beta1+mc1.21]</li> 	<li>Indium [1.0.33+mc1.21]</li> 	<li>No Chat Reports [1.21-v2.8.0]</li> 	<li>Xaero's World Map [1.38.8]</li> 	<li>NotEnoughAnimations [1.7.4]</li> 	<li>Dynamic Crosshair [8.0.1+1.21]</li> 	<li>Cloth Config v15 [15.0.127]</li> 	<li>Entity Texture Features [6.1.1]</li> 	<li>Just Enough Items [19.0.0.1]</li> 	<li>Scoreboard Overhaul [1.1.3-mc1.21.0]</li> 	<li>Reese's Sodium Options [1.7.2+mc1.21]</li> 	<li>3d-Skin-Layers [1.6.6]</li> 	<li>Fabric Language Kotlin [1.11.0+kotlin.2.0.0]</li> 	<li>BetterF3 [11.0.0]</li> 	<li>Iris [1.7.1+mc1.21]</li> 	<li>AppleSkin [3.0.2+mc1.21]</li> 	<li>Simple Voice Chat [1.21-2.5.16]</li> 	<li>Configured [2.5.0]</li> 	<li>Fabric API [0.100.4+1.21]</li> 	<li>Continuity [3.0.0-beta.5+1.21]</li> 	<li>Distant Horizons [2.1.2-a]</li> 	<li>AutoRun [0.6.0]</li> 	<li>Force Crawl [1.0.4]</li> 	<li>Searchables [1.0.1]</li> 	<li>Controlling [18.0.1]</li>

### To Reproduce (If applicable)

Have both mod in client and server, try moving, crashes server

### Additional Information

I was running shaders and Distant Horizons so my server could just be overloading

**Comment by FamroFexl** [comment]
Do you have any crash logs?

**Comment by TheRubyGames** [comment]
> Do you have any crash logs?

Yeah I do!
[crash-2024-07-04_18.23.11-server.txt](https://github.com/user-attachments/files/16103490/crash-2024-07-04_18.23.11-server.txt)

**Comment by FamroFexl** [comment]
Try this release:
https://github.com/FamroFexl/ForceCrawl/releases/tag/v1.0.5

It might have been improper arguments in the network packets.

**Comment by TheRubyGames** [comment]
> Try this release: https://github.com/FamroFexl/ForceCrawl/releases/tag/v1.0.5
> 
> It might have been improper arguments in the network packets.

Works perfect! And players who don't have this mod can still join the server?

**Comment by FamroFexl** [comment]
I believe so. Players just won't be able to "force" themselves into a crawling pose without it.
