### ISSUE TITLE
[Bug]: Configuration file path broken on Linux (likely true on Mac as well)

### ISSUE THREAD

**Issue by kkempfer** [FamroFexl/ForceCrawl#9]
### Describe the Bug

On Linux, the file path is stored as 'config\forcecrawl.cfg' file under the instance directory instead of being 'forcecrawl.cfg' inside the 'config' dir. It seems that the path is hardcoded for Windows OS only.

### Mod version(s) affected

1.0.2

### Mod loader(s) used

Fabric

### Minecraft version(s) used

v1.19.2

### Other mods used

Fabric API

### To Reproduce (If applicable)

To reproduce, install the mod on a Linux (or Mac) machine.

**Comment by FamroFexl** [comment]
This fix was found in #4 and implemented in 9c49a90, but was never released because the manual config was discarded in the a00e63e 1.20 release onward. I could upload it if it is required for the modpack.

**Comment by FamroFexl** [comment]
Also, the mod still currently has a bug that prevents it from being functionally used on Open to LAN worlds (see #3). I don't plan on fixing this issue.

**Comment by kkempfer** [comment]
Oh my bad, I didn't check closed tickets before creating this one. If it is not too much work, it would be nice if you would upload the fix for 1.19.2. I would love to feature the mod in my modpack.

Thank you for letting me know about the LAN issue. Version 1 of the modpack will target single player worlds. I might do a multiplayer edition further down the line. Maybe I will remove your mod from this special version. Testing is required.

**Comment by FamroFexl** [comment]
[Modrinth](https://modrinth.com/mod/force-crawl/version/il0BScx7)
Curseforge: Approval pending
